version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55000:3000"  # Extern port 3000 → intern port 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped